all: qsort bsearch shuffle

qsort: qsort.c
	gcc qsort.c -o qsort -g

bsearch: bsearch.c
	gcc bsearch.c -o bsearch -g

shuffle: shuffle.c
	gcc shuffle.c -o shuffle -g

clean:
	rm qsort
	rm bsearch
	rm shuffle